In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
pd.set_option('display.max_columns', None)
df = pd.read_csv('EDA_format.csv', index_col=0)
df

,rooms_count,type_rooms,city,address,floor,all_floor,repair,balcon,ceil,trash,metro_station,time_to_metro,all_squar,live_squar,kitchen_squar,ptice_month,util_service,bail,rent_period,prepayment,pas_lift,freight_lift,сhild_allow,pets_allow,child_pets_allow,bathrooms,type_bathrooms
id,,,,,,,,,,,,,,,,,,,,,,,,,,,
271271157,4.0,Неизвестно,Москва,"улица Новый Арбат, 27",5,16,Дизайнерский,Лоджия (1),3.00,Да,Смоленская,9,200.0,20.0,20.000000,500000,1,500000,1,1,4,1,нет,нет,нет,1.0,Нет
271634126,4.0,Неизвестно,Москва,"улица Новый Арбат, 27",5,16,Дизайнерский,Лоджия (1),3.50,Нет,Смоленская,8,198.0,95.0,18.000000,500000,1,500000,1,1,1,1,да,нет,нет,3.0,Совмещенный и Раздельный
271173086,4.0,Оба варианта,Москва,"улица Новый Арбат, 27",5,16,Евроремонт,Лоджия (1),3.20,Да,Смоленская,7,200.0,116.0,4.000000,500000,0,500000,1,1,1,0,да,нет,нет,3.0,Совмещенный
272197456,4.0,Оба варианта,Москва,"переулок Плотников, 21С1",5,6,Евроремонт,Балкон (1),3.20,Да,Смоленская,3,170.0,95.0,17.000000,400000,0,400000,1,1,1,0,нет,да,нет,3.0,Совмещенный
273614615,2.0,Неизвестно,Москва,"улица Новый Арбат, 15",12,26,Евроремонт,"Балкон (1), Лоджия (1)",3.90,Да,Арбатская,7,58.0,38.0,5.000000,225000,1,225000,1,1,1,1,нет,нет,да,2.0,Совмещенный
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215565511,0.0,Неизвестно,Москва,"Боровское шоссе, 2к7, ш. Боровское (3 км до МК...",10,14,Евроремонт,Балкон (1),1.20,Да,Говорово,8,35.0,16.4,8.000000,42000,1,42000,1,1,1,1,нет,нет,да,1.0,Совмещенный
274654844,1.0,Неизвестно,Москва,"Производственная улица, 8к1, ш. Боровское (5 к...",5,18,Евроремонт,Лоджия (1),2.70,Нет,Солнцево,7,38.7,16.5,11.000000,45000,1,45000,1,1,1,1,нет,нет,да,1.0,Совмещенный
268679909,2.0,Оба варианта,Москва,"Боровский проезд, 11",5,5,Дизайнерский,Балкон (1),1.20,Нет,Солнцево,6,43.1,20.0,11.635887,50000,1,50000,1,1,0,0,да,нет,нет,1.0,Совмещенный
274807525,2.0,Неизвестно,Москва,"улица Богданова, 6к1, ш. Боровское (3 км до МК...",8,23,Евроремонт,Лоджия (1),2.65,Да,Солнцево,11,52.5,20.0,10.000000,55000,1,50000,1,2,3,0,нет,нет,да,2.0,Совмещенный и Раздельный
274672243,2.0,Оба варианта,Москва,"улица Богданова, 2к1, ш. Боровское (3 км до МК...",6,23,Косметический,Лоджия (1),1.20,Да,Говорово,10,90.0,48.2,15.500000,57000,1,60000,1,1,3,0,нет,нет,нет,1.0,Раздельный

In [3]:
replace_dict = {
    'да': 1,
    'Да': 1,
    'нет': 0,
    'Нет': 0
}

# Замена значений во всем датафрейме
df.replace(replace_dict, inplace=True)
df.head()

/tmp/ipykernel_25117/3090768174.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(replace_dict, inplace=True)

,rooms_count,type_rooms,city,address,floor,all_floor,repair,balcon,ceil,trash,metro_station,time_to_metro,all_squar,live_squar,kitchen_squar,ptice_month,util_service,bail,rent_period,prepayment,pas_lift,freight_lift,сhild_allow,pets_allow,child_pets_allow,bathrooms,type_bathrooms
id,,,,,,,,,,,,,,,,,,,,,,,,,,,
271271157,4.0,Неизвестно,Москва,"улица Новый Арбат, 27",5,16,Дизайнерский,Лоджия (1),3.0,1,Смоленская,9,200.0,20.0,20.0,500000,1,500000,1,1,4,1,0,0,0,1.0,0
271634126,4.0,Неизвестно,Москва,"улица Новый Арбат, 27",5,16,Дизайнерский,Лоджия (1),3.5,0,Смоленская,8,198.0,95.0,18.0,500000,1,500000,1,1,1,1,1,0,0,3.0,Совмещенный и Раздельный
271173086,4.0,Оба варианта,Москва,"улица Новый Арбат, 27",5,16,Евроремонт,Лоджия (1),3.2,1,Смоленская,7,200.0,116.0,4.0,500000,0,500000,1,1,1,0,1,0,0,3.0,Совмещенный
272197456,4.0,Оба варианта,Москва,"переулок Плотников, 21С1",5,6,Евроремонт,Балкон (1),3.2,1,Смоленская,3,170.0,95.0,17.0,400000,0,400000,1,1,1,0,0,1,0,3.0,Совмещенный
273614615,2.0,Неизвестно,Москва,"улица Новый Арбат, 15",12,26,Евроремонт,"Балкон (1), Лоджия (1)",3.9,1,Арбатская,7,58.0,38.0,5.0,225000,1,225000,1,1,1,1,0,0,1,2.0,Совмещенный

In [17]:
label_encoders = {}
categorical_columns = [
    'type_rooms', 'city', 'address', 'repair', 
    'balcon', 'metro_station', 'time_to_metro',
    'rent_period', 'pas_lift', 'freight_lift', 
    'type_bathrooms'
]
for column in categorical_columns:
    df[column] = df[column].astype(str) 
label_encoders = {}

for column in categorical_columns:
    le = LabelEncoder()
    df[column + '_encoded'] = le.fit_transform(df[column])
    label_encoders[column] = le

In [18]:
df = df.drop(['type_rooms', 
              'address', 
              'city', 
              'repair', 
              'balcon', 
              'metro_station', 
              'rent_period', 
              'pas_lift', 
              'freight_lift', 
              'type_bathrooms'], 
             axis=1
            )
df

,rooms_count,floor,all_floor,ceil,trash,time_to_metro,all_squar,live_squar,kitchen_squar,ptice_month,util_service,bail,prepayment,сhild_allow,pets_allow,child_pets_allow,bathrooms,type_rooms_encoded,city_encoded,address_encoded,repair_encoded,balcon_encoded,metro_station_encoded,time_to_metro_encoded,rent_period_encoded,pas_lift_encoded,freight_lift_encoded,type_bathrooms_encoded
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,
271271157,4.0,5,16,3.00,1,9,200.0,20.0,20.000000,500000,1,500000,1,0,0,0,1.0,1,1,11794,1,14,253,63,1,4,1,0
271634126,4.0,5,16,3.50,0,8,198.0,95.0,18.000000,500000,1,500000,1,1,0,0,3.0,1,1,11794,1,14,253,62,1,1,1,3
271173086,4.0,5,16,3.20,1,7,200.0,116.0,4.000000,500000,0,500000,1,1,0,0,3.0,2,1,11794,2,14,253,59,1,1,0,2
272197456,4.0,5,6,3.20,1,3,170.0,95.0,17.000000,400000,0,400000,1,0,1,0,3.0,2,1,8774,2,0,253,24,1,1,0,2
273614615,2.0,12,26,3.90,1,7,58.0,38.0,5.000000,225000,1,225000,1,0,0,1,2.0,1,1,11791,2,1,13,59,1,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215565511,0.0,10,14,1.20,1,8,35.0,16.4,8.000000,42000,1,42000,1,0,0,1,1.0,1,1,1482,2,0,61,62,1,1,1,2
274654844,1.0,5,18,2.70,0,7,38.7,16.5,11.000000,45000,1,45000,1,0,0,1,1.0,1,1,5883,2,14,257,59,1,1,1,2
268679909,2.0,5,5,1.20,0,6,43.1,20.0,11.635887,50000,1,50000,1,1,0,0,1.0,2,1,1459,1,0,257,52,1,0,0,2
274807525,2.0,8,23,2.65,1,11,52.5,20.0,10.000000,55000,1,50000,2,0,0,1,2.0,1,1,10040,2,14,257,3,1,3,0,3
274672243,2.0,6,23,1.20,1,10,90.0,48.2,15.500000,57000,1,60000,1,0,0,0,1.0,2,1,10033,3,14,61,2,1,3,0,1

In [19]:
df.to_csv('EDA_Releas3.csv', index=False)